AcademiaCintia/AcademiaCintia/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace AcademiaCintia.Controllers;

[Authorize(Roles = "Administrador, Funcionário")]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;

    public AdminController(ILogger<AdminController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View("Error!");
    }
}

AcademiaCintia/AcademiaCintia/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademiaCintia.Data;
using AcademiaCintia.Models;

namespace AcademiaCintia.Controllers
{
    public class ComentarioController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ComentarioController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }


        // GET: Comentario
        public async Task<IActionResult> Index()
        {
              return View(await _context.Comentarios.ToListAsync());
        }

        // GET: Comentario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // GET: Comentario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Comentario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,ComentarioTexto,ComentarioData,Nota,Foto")] Comentario comentario, IFormFile formFile)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comentario);
                await _context.SaveChangesAsync();
                if (formFile != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = comentario.Id.ToString("00") + Path.GetExtension(formFile.FileName);
                    string uploads = Path.Combine(wwwRootPath, @"img\testimonial");
                    string newFile = Path.Combine(uploads, fileName);
                    using (var stream = new FileStream(newFile, FileMode.Create))
                    {
                        formFile.CopyTo(stream);
                    }
                    comentario.Foto = @"\img\testimonial\" + fileName;
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comentario);
        }

        // GET: Comentario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios.FindAsync(id);
            if (comentario == null)
            {
                return NotFound();
            }
            return View(comentario);
        }

        // POST: Comentario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,ComentarioTexto,ComentarioData,Nota,Foto")] Comentario comentario, IFormFile formFile)
        {
            if (id != comentario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (formFile != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        if (comentario.Foto != null)
                        {
                            string oldFile = Path.Combine(wwwRootPath, comentario.Foto.TrimStart('\\'));
                            if (System.IO.File.Exists(oldFile))
                            {
                                System.IO.File.Delete(oldFile);
                            }
                        }

                        string fileName = comentario.Id.ToString("00") + Path.GetExtension(formFile.FileName);
                        string uploads = Path.Combine(wwwRootPath, @"img\testimonial");
                        string newFile = Path.Combine(uploads, fileName);
                        using (var stream = new FileStream(newFile, FileMode.Create))
                        {
                            formFile.CopyTo(stream);
                        }
                        comentario.Foto = @"\img\testimonial\" + fileName;
                    }
                    _context.Update(comentario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComentarioExists(comentario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(comentario);
        }

        // GET: Comentario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Comentarios == null)
            {
                return NotFound();
            }

            var comentario = await _context.Comentarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comentario == null)
            {
                return NotFound();
            }

            return View(comentario);
        }

        // POST: Comentario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Comentarios == null)
            {
                return Problem("Entity set 'AppDbContext.Comentarios'  is null.");
            }
            var comentario = await _context.Comentarios.FindAsync(id);
            if (comentario != null)
            {
                _context.Comentarios.Remove(comentario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComentarioExists(int id)
        {
          return _context.Comentarios.Any(e => e.Id == id);
        }
    }
}

AcademiaCintia/AcademiaCintia/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademiaCintia.Data;
using AcademiaCintia.Models;

namespace AcademiaCintia.Controllers
{
    public class ProfessorController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProfessorController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }


        // GET: Professor
        public async Task<IActionResult> Index()
        {
              return View(await _context.Professores.ToListAsync());
        }

        // GET: Professor/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Professores == null)
            {
                return NotFound();
            }

            var professor = await _context.Professores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // GET: Professor/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Professor/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cargo,Foto,Facebook,Instagram")] Professor professor, IFormFile formFile)
        {
            if (ModelState.IsValid)
            {
                _context.Add(professor);
                await _context.SaveChangesAsync();
                if (formFile != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = professor.Id.ToString("00") + Path.GetExtension(formFile.FileName);
                    string uploads = Path.Combine(wwwRootPath, @"img\team");
                    string newFile = Path.Combine(uploads, fileName);
                    using (var stream = new FileStream(newFile, FileMode.Create))
                    {
                        formFile.CopyTo(stream);
                    }
                    professor.Foto = @"\img\team\" + fileName;
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professor/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Professores == null)
            {
                return NotFound();
            }

            var professor = await _context.Professores.FindAsync(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }

        // POST: Professor/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Cargo,Foto,Facebook,Instagram")] Professor professor, IFormFile formFile)
        {
            if (id != professor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (formFile != null)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        if (professor.Foto != null)
                        {
                            string oldFile = Path.Combine(wwwRootPath, professor.Foto.TrimStart('\\'));
                            if (System.IO.File.Exists(oldFile))
                            {
                                System.IO.File.Delete(oldFile);
                            }
                        }

                        string fileName = professor.Id.ToString("00") + Path.GetExtension(formFile.FileName);
                        string uploads = Path.Combine(wwwRootPath, @"img\team");
                        string newFile = Path.Combine(uploads, fileName);
                        using (var stream = new FileStream(newFile, FileMode.Create))
                        {
                            formFile.CopyTo(stream);
                        }
                        professor.Foto = @"\img\team\" + fileName;
                    }
                    _context.Update(professor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        // GET: Professor/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Professores == null)
            {
                return NotFound();
            }

            var professor = await _context.Professores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        // POST: Professor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Professores == null)
            {
                return Problem("Entity set 'AppDbContext.Professores'  is null.");
            }
            var professor = await _context.Professores.FindAsync(id);
            if (professor != null)
            {
                _context.Professores.Remove(professor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessorExists(int id)
        {
          return _context.Professores.Any(e => e.Id == id);
        }
    }
}

AcademiaCintia/AcademiaCintia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Gym Template">
    <meta name="keywords" content="Gym, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="~/img/logo.png" />
    <title>ACADEMIA CINTIA RECO</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/flaticon.css" type="text/css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/barfiller.css" type="text/css">
    <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
    <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Section Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="canvas-close">
            <i class="fa fa-close"></i>
        </div>
        <div class="canvas-search search-switch">
            <i class="fa fa-search"></i>
        </div>
        <nav class="canvas-menu mobile-menu">
            <ul>
                <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                            <li><a asp-action="SobreNos" asp-controller="Home">Sobre Nós</a></li>
                            <li><a asp-action="Horarios" asp-controller="Home">Horários</a></li>
                            <li><a asp-action="Modalidades" asp-controller="Home">Modalidades</a></li>
                            <li><a asp-action="NossoTime" asp-controller="Home">Nosso Time</a></li>
                            <li><a href="#">Páginas</a>
                                <ul class="dropdown">
                                    <li><a asp-action="TesteIMC" asp-controller="Home">Teste de IMC</a></li>
                                    <li><a asp-action="Galeria" asp-controller="Home">Galeria</a></li>
                                </ul>
                            </li>
                            <li><a asp-action="Contato" asp-controller="Home">Contato</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="canvas-social">
            <a href="https://www.facebook.com/profile.php?id=100005450629244"><i class="fa fa-facebook"></i></a>
            <a href="https://www.youtube.com/@@MultiCintilante"><i class="fa fa-youtube-play"></i></a>
            <a href="https://www.instagram.com/academiacintia/"><i class="fa fa-instagram"></i></a>
        </div>
    </div>
    <!-- Offcanvas Menu Section End -->

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3">
                    <div class="logo">
                        <a asp-action="Index" asp-controller="Home">
                            <img src="~/img/logo.png" alt="" width="70">
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="nav-menu">
                        <ul>
                            <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                            <li><a asp-action="SobreNos" asp-controller="Home">Sobre Nós</a></li>
                            <li><a asp-action="Horarios" asp-controller="Home">Horários</a></li>
                            <li><a asp-action="Modalidades" asp-controller="Home">Modalidades</a></li>
                            <li><a asp-action="NossoTime" asp-controller="Home">Nosso Time</a></li>
                            <li><a href="#">Páginas</a>
                                <ul class="dropdown">
                                    <li><a asp-action="TesteIMC" asp-controller="Home">Teste de IMC</a></li>
                                    <li><a asp-action="Galeria" asp-controller="Home">Galeria</a></li>
                                </ul>
                            </li>
                            <li><a asp-action="Contato" asp-controller="Home">Contato</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="top-option">
                        <div class="to-social">
                            <a href="https://www.facebook.com/profile.php?id=100005450629244"><i class="fa fa-facebook"></i></a>
                            <a href="https://www.youtube.com/@@MultiCintilante"><i class="fa fa-youtube-play"></i></a>
                            <a href="https://www.instagram.com/academiacintia/"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="canvas-open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header End -->

    @RenderBody()

    <!-- Footer Section Begin -->
    <section class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="fs-about">
                        <p>Treinar é sentir que você pode fazer algo que depende do seu esforço e da sua determinação.
                            Quanto mais motivado você estiver, melhores vão ser os resultados!</p>
                        <p>HORÁRIO DE FUNCIONAMENTO: <strong>06h-11h/14h30-21h</strong></p>
                        <div class="fa-social">
                            <a href="https://www.facebook.com/profile.php?id=100005450629244"><i
                                    class="fa fa-facebook"></i></a>
                            <a href="https://www.youtube.com/@@MultiCintilante"><i class="fa fa-youtube-play"></i></a>
                            <a href="https://www.instagram.com/academiacintia/"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
    </section>
    <!-- Footer Section End -->

    <!-- Search model Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search model end -->

    <!-- Js Plugins -->
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/masonry.pkgd.min.js"></script>
    <script src="~/js/jquery.barfiller.js"></script>
    <script src="~/js/jquery.slicknav.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

AcademiaCintia/AcademiaCintia/Views/Shared/_LayoutAccount.cshtml
<!doctype html>
<html lang="pt-br" data-bs-theme="auto">
  <head>
    <script src="~/js/color-modes.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ACADEMIA CINTIA RECO| @ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/account.css">
    @await RenderSectionAsync("Styles", required: false)
  </head>
  <body>
    @RenderBody()

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.9.0/dist/sweetalert2.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
  </body>
</html>

AcademiaCintia/AcademiaCintia/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">

<head>
    <script src="~/js/color-modes.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ACADEMIA CINTIA RECO | @ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="~/img/logo.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    @await RenderSectionAsync("Styles", required: false)
    <meta name="theme-color" content="#712cf9">
</head>

<body>
    <partial name="_StyleSwitcher"></partial>
    <partial name="_Loading"></partial>

    <div class="container-fluid p-0">
        <main role="main" class="d-flex flex-nowrap">
            <div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3" style="width: 280px;">
                <a asp-action="Index" asp-controller="Admin"
                    class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                    <img class="img-fluid" src="~/img/logo.png" alt="Logo" width="25">
                    <h1 class="fs-5 m-0 ms-3 ">Academia Cintia Reco</h1>
                </a>
                <hr>
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="Admin" class="nav-link @(ViewBag.Title == "Painel" ? "active" : "link-body-emphasis")">
                            <i class="bi bi-list-stars me-2"></i>
                            Painel
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Modalidade" class="nav-link @(ViewBag.Title == "Modalidade" ? "active" : "link-body-emphasis")">
                            <i class="bi bi-house me-2"></i>
                            Modalidade
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Professor" class="nav-link @(ViewBag.Title == "Professor" ? "active" : "link-body-emphasis")">
                            <i class="bi bi-people-fill me-2"></i>
                            Professores
                        </a>
                    </li>
                     <li>
                        <a asp-action="Index" asp-controller="Comentario" class="nav-link @(ViewBag.Title == "Comentario" ? "active" : "link-body-emphasis")">
                            <i class="bi bi-chat-left-heart-fill me-2"></i>
                            Comentario
                        </a>
                    </li>
                    <li>
                        <a asp-action="Index" asp-controller="Galeria" class="nav-link @(ViewBag.Title == "Galeria" ? "active" : "link-body-emphasis")">
                            <i class="bi bi-images me-2"></i>
                            Galeria
                        </a>
                    </li>
                </ul>
                <hr>
                <partial name="_LoginPartialAdmin"></partial>
            </div>

            <div class="container-fluid py-2">
                <nav class="navbar sticky-top border-bottom">
                    <button id="sidebarToggler" class="navbar-toggler border-0 p-0" type="button" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </nav>
                <div class="container-fluid p-3">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

AcademiaCintia/AcademiaCintia/Views/Shared/_Loading.cshtml
<div id="loading">
    <div class="loader simple-loader">
        <img src="~/img/icon-deal.png">
        <h1 class="text-center text-white">&nbsp;&nbsp; Processando...</h1>
    </div>
</div>

AcademiaCintia/AcademiaCintia/Views/Shared/_LoginPartialAdmin.cshtml
@inject AcademiaCintia.Services.IUsuarioService userService
@{
    var usuario = await userService.GetUsuarioLogado();
}

<div class="dropdown w-100" >
    <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle"
        data-bs-toggle="dropdown" aria-expanded="false">
        <img src='@(usuario.Foto ?? "~/img/users/no-photo.png")' alt="Foto de Perfil" width="40" class="image-rounded me-3">
        <strong>@User.Identity?.Name</strong>
    </a>
    <ul class="dropdown-menu text-small shadow w-100">
        <li><a class="dropdown-item" href="#">Perfil</a></li>
        <li><a class="dropdown-item" href="#">Configurações</a></li>
        <li>
            <hr class="dropdown-divider">
        </li>
        <li>
            <form class="form-inline" asp-controller="Account" asp-action="Logout">
                <button type="submit" class="dropdown-item">
                    Sair
                </button>
            </form>
        </li>
    </ul>
</div>